package ru.mirea.dentalclinic.util;

import ru.mirea.dentalclinic.exception.DatabaseException;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Подключение к базе данных (H2, in-memory) и создание схемы.
 *
 * Репозитории вызывают {@link #getConnection()} и закрывают соединение
 * через try-with-resources. База в памяти живёт, пока работает программа
 * (DB_CLOSE_DELAY=-1 не даёт ей исчезнуть между соединениями).
 *
 * Чтобы данные сохранялись между запусками, замените URL на файловый:
 * jdbc:h2:file:./data/dentalclinic
 */
public final class DatabaseManager {

    private static final String URL = "jdbc:h2:mem:dentalclinic;DB_CLOSE_DELAY=-1";
    private static final String USER = "sa";
    private static final String PASSWORD = "";

    private static final String[] SCHEMA = {
            """
            CREATE TABLE IF NOT EXISTS patients (
                id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                full_name  VARCHAR(120) NOT NULL,
                phone      VARCHAR(20)  NOT NULL,
                email      VARCHAR(120),
                birth_date DATE         NOT NULL,
                created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS dentists (
                id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                full_name      VARCHAR(120) NOT NULL,
                phone          VARCHAR(20)  NOT NULL,
                specialization VARCHAR(100) NOT NULL,
                cabinet        INT          NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS appointments (
                id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                patient_id       INT           NOT NULL,
                dentist_id       INT           NOT NULL,
                appointment_time TIMESTAMP     NOT NULL,
                procedure_type   VARCHAR(30)   NOT NULL,
                status           VARCHAR(20)   NOT NULL,
                price            DECIMAL(10,2) NOT NULL,
                complaint        VARCHAR(255),
                created_at       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
                CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id)
                    REFERENCES patients (id) ON DELETE CASCADE,
                CONSTRAINT fk_appointment_dentist FOREIGN KEY (dentist_id)
                    REFERENCES dentists (id) ON DELETE RESTRICT
            )
            """
    };

    private static boolean initialized = false;

    private DatabaseManager() {
    }

    /** Создаёт таблицы, если их ещё нет. Безопасно вызывать много раз. */
    public static synchronized void init() {
        if (initialized) {
            return;
        }
        try (Connection connection = open();
             Statement statement = connection.createStatement()) {
            for (String ddl : SCHEMA) {
                statement.execute(ddl);
            }
            initialized = true;
        } catch (SQLException e) {
            throw new DatabaseException("не удалось создать таблицы базы данных: " + e.getMessage(), e);
        }
    }

    /** Новое соединение; вызывающий код обязан закрыть его (try-with-resources). */
    public static Connection getConnection() throws SQLException {
        init();
        return open();
    }

    private static Connection open() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASSWORD);
    }
}
